### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bingcao2** [flatironinstitute/CaImAn#242]
I can successfully run the demo_pipeline_cnmfE.py in the demos/general folder, however, often raise the IndexError: list index out of range when I tried to use my endoscope .tif file to do the motion correction. My operating system is macOS High Sierra (10.13.4) and python version is 3.6 in anaconda caiman virtual env and always use spyder to run ipython for the code. 
I have read the issues#90 but I feel the previous guidance is not enough to help me fix the current problem.
I appreciate your help and please find the error traceback as follows. Thank you very much!

Code:
```
if do_motion_correction_nonrigid or do_motion_correction_rigid:
    # do motion correction rigid
    mc = motion_correct_oneP_rigid(fnames,                        # name of file to motion correct
                                   # size of filter, xhange this one if
                                   # algorithm does not work
                                   gSig_filt=[gSig] * 2,
                                   # maximum shifts allowed in each direction
                                   max_shifts=[5, 5],
                                   dview=dview,
                                   # number of chunks for parallelizing motion correction (remember that it should hold that length_movie/num_splits_to_process_rig>100)
                                   splits_rig=10,
                                   save_movie=not(do_motion_correction_nonrigid)
                                   )
```

```
Traceback (most recent call last):

  File "<ipython-input-5-738f4e5f4235>", line 12, in <module>
    save_movie=not(do_motion_correction_nonrigid)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 491, in motion_correct_oneP_rigid
    mc.motion_correct_rigid(save_movie=save_movie, template=new_templ)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 243, in motion_correct_rigid
    use_cuda=self.use_cuda)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 2185, in motion_correct_batch_rigid
    use_cuda=use_cuda)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 2476, in motion_correction_piecewise
    res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)

  File "/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

IndexError: list index out of range
```

**Comment by epnev** [comment]
@bingcao2 This also looks very familiar to issue https://github.com/flatironinstitute/CaImAn/issues/232 
Have you installed CaImAn using the pip installer?

**Comment by bingcao2** [comment]
Thanks a lot for your prompt reply. Yes! I have installed the CaImAn by 
`pip -install -e .` 
as well as 
`python caimanmanager.py install --inplace`

Before the latest update, I could run the motion correction but not other CNMF functions. Right now I could run all the demo data in the caiman_data folder, such as demoMovie.tif and Sue_2x_3000_40_-46.tif, but not on my data. I used two data set which one is 1000 frames of 752*480 pixels in 8-bit and the other is 1000f of 128*128 pixels in 32-bit.

**Comment by bingcao2** [comment]
@agiovann 
Sure! Here it is.
`#%% motion correction
if do_motion_correction_nonrigid or do_motion_correction_rigid:
    # do motion correction rigid
    mc = motion_correct_oneP_rigid(fnames,                        # name of file to motion correct
                                   # size of filter, xhange this one if
                                   # algorithm does not work
                                   gSig_filt=[gSig] * 2,
                                   # maximum shifts allowed in each direction
                                   max_shifts=[5, 5],
                                   dview=None,
                                   # number of chunks for parallelizing motion correction (remember that it should hold that length_movie/num_splits_to_process_rig>100)
                                   splits_rig=10,
                                   save_movie=not(do_motion_correction_nonrigid)
                                   )`

`Rigid Motion Correction
0.334047
Frame 100
cubic interpolation
Frame 100
Frame 100
cubic interpolation
Frame 100
Frame 100
cubic interpolation
Frame 100
Adding to movie 0.334047
0
saving!
Traceback (most recent call last):

  File "<ipython-input-5-a81bad55200a>", line 12, in <module>
    save_movie=not(do_motion_correction_nonrigid)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 491, in motion_correct_oneP_rigid
    mc.motion_correct_rigid(save_movie=save_movie, template=new_templ)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 243, in motion_correct_rigid
    use_cuda=self.use_cuda)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 2185, in motion_correct_batch_rigid
    use_cuda=use_cuda)

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 2481, in motion_correction_piecewise
    res = list(map(tile_and_correct_wrapper, pars))

  File "/Users/Bing/CaImAn/caiman/motion_correction.py", line 2344, in tile_and_correct_wrapper
    imgs = imread(img_name, key=idxs)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/skimage/external/tifffile/tifffile.py", line 1234, in imread
    return tif.asarray(**kwargs)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/skimage/external/tifffile/tifffile.py", line 1487, in asarray
    pages = [pages[k] for k in key]

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/skimage/external/tifffile/tifffile.py", line 1487, in <listcomp>
    pages = [pages[k] for k in key]

IndexError: list index out of range`

Many thanks for your help!

**Comment by agiovann** [comment]
@bingcao2 I think I might have a better solution. Can you use caiman to resave the file. something like the following:
``` python
mov = cm.load('your_imagej_file.tif')
mov.save('new_file_name.hdf5')
now use the newly saved file to run the analysis
```
Cheers

**Comment by epnev** [comment]
@bingcao2 See also the response in #237 regarding the tifffile package.

**Comment by bingcao2** [comment]
@agiovann Hi, I have tried the first solution to reinstall the tifffile=0.12. It will induce the same Error during using CNMF, just same as what I met in the previous version. So I plan to use your second better solution. Could you help me to update my tifffile to the latest one in CaImAn?
Thank you very much!

**Comment by epnev** [comment]
@bingcao2 I believe that after you update a package you might need to run again the pip installer. But I'm not sure. Perhaps @agiovann or @pgunn might know better.

**Comment by pgunn** [comment]
Modifying packages in the Conda python environment should not require reinstalling caiman.

**Comment by bingcao2** [comment]
Hi, all. I must to thank agiovann for his great idea to save as .hdf5 files! Many thanks for your genius!

**Comment by epnev** [comment]
The issue should be fixed now (without the need of resorting to .hdf5 files, which are great btw)

**Comment by Cumol** [comment]
@epnev this issue does not seem to be resolved yet as I still had to convert my .tif file to .hdf5 to continue the pipeline, even after updating to the newest version:
```

Running under iPython
tifffile package not found, using skimage instead for imsave
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-36d71db54762> in <module>()
----> 1 import codecs, os, ast;__pyfile = codecs.open('''/tmp/py985j6L''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py985j6L''');__block = ast.parse(__code, '''/home/generalubuntu/demo_pipeline.py''', mode='exec');__last = __block.body[-1];__isexpr = isinstance(__last,ast.Expr);__block.body.pop() if __isexpr else None;exec(compile(__block, '''/home/generalubuntu/demo_pipeline.py''', mode='exec'));eval(compile(ast.Expression(__last.value), '''/home/generalubuntu/demo_pipeline.py''', mode='eval')) if __isexpr else None

~/demo_pipeline.py in <module>()
    120 #%%% MOTION CORRECTION
    121 # first we create a motion correction object with the parameters specified
--> 122 min_mov = cm.load(fname[0], subindices=range(200)).min()
    123 # this will be subtracted from the movie to make it non-negative
    124 

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1219                         input_arr  = tffl.asarray(key=subindices[0])[:, subindices[1], subindices[2]]
   1220                     else:
-> 1221                         input_arr  = tffl.asarray(key=subindices)
   1222 
   1223 #                    elif type(subindices) is range:

~/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py in asarray(self, key, series, out, maxworkers)
   1806             pages = pages[key]
   1807         elif isinstance(key, collections.Iterable):
-> 1808             pages = [pages[k] for k in key]
   1809         else:
   1810             raise TypeError('key must be an int, slice, or sequence')

~/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py in <listcomp>(.0)
   1806             pages = pages[key]
   1807         elif isinstance(key, collections.Iterable):
-> 1808             pages = [pages[k] for k in key]
   1809         else:
   1810             raise TypeError('key must be an int, slice, or sequence')

~/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py in __getitem__(self, key)
   2940             return page
   2941 
-> 2942         self._seek(key)
   2943         page = self._tiffpage(self.parent, index=key, keyframe=self._keyframe)
   2944         if self._cache:

~/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py in _seek(self, index)
   2901 
   2902         if index >= len(pages):
-> 2903             raise IndexError('list index out of range')
   2904 
   2905         page = pages[index]

IndexError: list index out of range

```

**Comment by agiovann** [comment]
Dear @Cumol it is probably your version of tifffile, in my hands it works after typing in my environment:

conda update -c conda-forge tifffile

Let me know if this is OK

**Comment by Cumol** [comment]
@agiovann still getting the same message/error, even after updating conda and tifffile...

`tifffile package not found, using skimage instead for imsave`

**Comment by HagaiHargil** [comment]
I believe this warning is due to a misplacement of this [line](https://github.com/flatironinstitute/CaImAn/blob/bbfacfef7f895469101706022dc358afe5e9550a/caiman/base/timeseries.py#L47):

```python
try:
    import tifffile
    print('tifffile package not found, using skimage instead for imsave')
except:
from skimage.external import tifffile
```
The `print` should come in the `except` block. The `tifffile` import might actually be successful.

**Comment by agiovann** [comment]
@Cumol apart from the warning, did you get rid of the error?

**Comment by Cumol** [comment]
No, I am still getting the exact same error message.

**Comment by pgunn** [comment]
@Cumol Hi,can you send us the output of the following command (run in your caiman conda environment)?
`conda list tifffile`

**Comment by Cumol** [comment]
```
# packages in environment at /home/generalubuntu/anaconda3/envs/caiman:
#
# Name                    Version                   Build  Channel
tifffile                  0.14.0                   py36_1    conda-forge
```

**Comment by agiovann** [comment]
@Cumol is this solved?

**Comment by Cumol** [comment]
@agiovann no, still have to go through .hdf5. only happens when using subindices; here is the error i get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py", line 1237, in load
    input_arr  = tffl.asarray(key=subindices)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py", line 1808, in asarray
    pages = [pages[k] for k in key]
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py", line 1808, in <listcomp>
    pages = [pages[k] for k in key]
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py", line 2942, in __getitem__
    self._seek(key)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/tifffile/tifffile.py", line 2903, in _seek
    raise IndexError('list index out of range')
IndexError: list index out of range
```

**Comment by MarkCBenz** [comment]
Can someone please provide more detailed instructions showing how to update the code in the CNMF-E pipeline in order to covert  .tiff files into the .hdf5 files that seem to work well with the motion correction algorithm. When I use:
'''
mov = cm.load('Demo_1_2.tif')
mov.save('Demo_1_2.hdf5')
'''
for instance, this is what I see:
'''
Exception                                 Traceback (most recent call last)
<ipython-input-7-d5343e22ca29> in <module>()
      1 fnames = [download_demo(fnames[0])]
----> 2 mov = cm.load('Demo_1_2.tif')
      3 mov.save('Demo_1_2.hdf5')
      4 fnames = ['Demo_1_2.hdf5']

~\Anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1403         print('File is:')
   1404         print(file_name)
-> 1405         raise Exception('File not found!')
   1406 
   1407     return movie(input_arr.astype(outtype), fr=fr, start_time=start_time, file_name=os.path.split(file_name)[-1], meta_data=meta_data)

Exception: File not found!
'''

**Comment by agiovann** [comment]
Dear @MarkCBenz, would you mind trying

mov = cm.load(['Demo_1_2.tif'])
mov.save('Demo_1_2.hdf5')

**Comment by epnev** [comment]
@Cumol Thanks for the update. I was hoping it would work this time around. My bet is that there is something different with the tifffile package in your distribution but I cannot understand what this might be. I'm living it open.

If you want to track this down, you can start by putting a breakpoint in line 179 of `movies.py` and then type`self.shape` to see what the output is.

To put a breakpoint you can insert:
```
import pdb
pdb.set_trace()
```

**Comment by epnev** [comment]
I'm closing this issue because I believe it is solved with d83712501013442bebcc4bdf90ba12e4b21be01d. Long story short, imagej/fiji will generate single page tiff files if the size is greater than 4GB and should be avoided. Feel free to open a new issue if you have concerns about this.
