### ISSUE TITLE
Error in function 'circular_constraint'

### ISSUE THREAD

**Issue by sebastiantiesmeyer** [flatironinstitute/CaImAn#319]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Linux (Ubuntu 17), python 3.5, tested on spyder/notebook/command line

- **Describe the issue that you are experiencing**

Running the CNMF-E demo pipeline with in-house collected calcium data. 

Running a small, 2800x600x420 file: No problems experienced, great results.
Running a larger, possibly less consistent (concerning e.g. the physical structures in the image) 28000x600x420 file:
-with parallelization: execution freezes
-without parallelization: Execution throws an error when the input to 'circular_constraints(img_originals)' is too small.
The function is recursive, and at some points one of the input img_originals has a shape of 1 in one of the two dimensions. 'np.gradient' cannot compute, of course, and throws an error 'Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required'. 

- **Copy error log below**

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 153, in <module>
    extract_spikes(jobs[0],output_loc)

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 97, in extract_spikes
    cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 457, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1031, in greedyROI_corr
    swap_dim=True, save_video=save_video, video_name=video_name)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1481, in init_neurons_corr_pnr
    data_raw_box, ind_ctr, patch_dims)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1640, in extract_ac
    ai = circular_constraint(ai)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 1375, in circular_constraint
    tmp_img = circular_constraint(img[rmin:rmax, cmin:cmax])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 1366, in circular_constraint
    fy, fx = np.gradient(img)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1754, in gradient
    "Shape of array too small to calculate a numerical gradient, "

ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

**Comment by epnev** [comment]
@j-friedrich Have you encountered this? Any ideas?

**Comment by j-friedrich** [comment]
Never encountered this. No idea right off the top of my head.

**Comment by j-friedrich** [comment]
fixed in master and dev branches

**Comment by sebastiantiesmeyer** [comment]
I don't think your solution prevents shape-1 arrays from re-entering recursion

if at all, instead of 
`if (rmax - rmin) * (cmax - cmin) <=1`

it should be:
`if (rmax - rmin) <=1 or (cmax - cmin) <=1;`

with that fix, I get a whole number of complaints further up in the pipeline concerning inf/nan values during np.isfinite checks.

**e.g. spatial.py, ln 395:**

   _cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 457, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1074, in greedyROI_corr
    dview=None, **options['spatial_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 220, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 391, in regression_ipyparallel
    a_lrs = clf.fit(np.array(c.T), np.ravel(y))

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 699, in fit
    X, y = check_X_y(X, y, y_numeric=True, multi_output=True)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 576, in check_X_y
    dtype=None)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32')._

**or deconvolution.py, ln 1027**

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/temporal.py", line 233, in update_temporal_components
    ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/temporal.py", line 390, in update_iteration
    results = list(map(constrained_foopsi_parallel, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/temporal.py", line 64, in constrained_foopsi_parallel
    Ytemp, bl=bl, c1=c1, g=g, sn=sn, **argss)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/deconvolution.py", line 129, in constrained_foopsi
    method=noise_method, lags=lags, fudge_factor=fudge_factor)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/deconvolution.py", line 982, in estimate_parameters
    g = estimate_time_constant(fluor, p, sn, lags, fudge_factor)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/deconvolution.py", line 1026, in estimate_time_constant
    gr = np.roots(np.concatenate([np.array([1]), -g.flatten()]))

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 229, in roots
    roots = eigvals(A)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 904, in eigvals
    _assertFinite(a)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 216, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")


**or temporal.py, ln 416:**

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 97, in extract_spikes
    cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 457, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1080, in greedyROI_corr
    dview=None, bl=None, c1=None, sn=None, g=None, **o)[:2]

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/temporal.py", line 233, in update_temporal_components
    ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/temporal.py", line 416, in update_iteration
    if scipy.linalg.norm(Cin - C, 'fro') <= 1e-3 * scipy.linalg.norm(C, 'fro'):

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/linalg/misc.py", line 137, in norm
    a = np.asarray_chkfinite(a)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")

ValueError: array must not contain infs or NaNs

**Comment by j-friedrich** [comment]
@sebastiantiesmeyer My solution deals with shape-(1,>1) arrays in the recursion, hence no need to prevent this. Only  shape-(1,1) arrays must not reenter the recursion.

Shouldn't make a differecne, but does `if (rmax - rmin) <=1 or (cmax - cmin) <=1` fix the problem?

**Comment by sebastiantiesmeyer** [comment]
np.gradient calculates the gradient in all dimensions. No dimension is allowed a shape <2.
Using `if (rmax - rmin) <=1 or (cmax - cmin) <=1`, I get the np.isnan/isinf problems listed above.

**Comment by sebastiantiesmeyer** [comment]
Sorry, I did not realize you made changes elsewhere in the code;
You are right in every respect, anyway. Errors persist even without the two post-processing constraints. Sorry for mixing things up!

**Comment by j-friedrich** [comment]
It seems as if one component ends up empty (all zeros) and should be removed, but difficult to track down. Do you know at which step in the pipeline the error occurs? After merging? We do the removing in update_temporal and update_spatial, but not in merging if the merged component ends up being empty. Apparently thus far this has not happened, but I found some parameter settings where it actually does for our cnmfE demo.

**Comment by sebastiantiesmeyer** [comment]
I opened a new issue for the problem since they're probably not related:
https://github.com/flatironinstitute/CaImAn/issues/323
