### ISSUE TITLE
Pipeline produces NaNs (and breaks on them) for some parameter settings

### ISSUE THREAD

**Issue by sebastiantiesmeyer** [flatironinstitute/CaImAn#323]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Ubuntu 17, python 3.5, tested on Spyder,jupyter,command line

- **Describe the issue that you are experiencing**

Running the CNMF-E demo pipeline with in-house collected calcium data.

Running a small, 2800x600x420 file: No problems experienced, great results.
Running a larger, possibly less consistent (concerning e.g. the physical structures in the image) 28000x600x420 file:

With parallelization: pipeline freezes, some processes do not finish.
Without parallelization: The pipeline completes the following steps successfully, but creates intermediate results containing NaNs, which it cannot process:

```
memmap__d1_420_d2_600_d3_1_order_C_frames_28000_.mmap and saving to 32364_20170710_corrected.pkl
using 32 processes
Stopping  cluster to avoid unnencessary use of memory....
(28000, 420, 600)
using 32 processes
using 4000 pixels per process
using 5000 block_size
(80, 80)
(28000, 81, 81)
using 1 processes
using 1600 pixels per process
using 5000 block_size
preprocessing ...
checking if missing data
initializing ...
Roi Extraction...
One photon initialization..
/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py:1305: RuntimeWarning: divide by zero encountered in true_divide
  pnr = np.divide(data_max, noise_pixel)
/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py:1319: RuntimeWarning: invalid value encountered in multiply
  v_search = cn * pnr
/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/deconvolution.py:1025: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  g = np.linalg.lstsq(A, xc[lags + 1:])[0]
/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py:1555: RuntimeWarning: divide by zero encountered in true_divide
  pnr_box = np.divide(max_box, noise_box)
/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py:1571: RuntimeWarning: invalid value encountered in multiply
  v_search[r2_min:r2_max, c2_min:c2_max] = cn_box * pnr_box
0 neurons have been initialized
In total,  36 neurons were initialized.
Compute Background
Update Spatial
Initializing update of Spatial Components
computing the distance indicators
/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
memmaping
Updating Spatial Components using lasso lars
```

- **Copy error log below**

Traceback (most recent call last):

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 97, in extract_spikes
    cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 457, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1074, in greedyROI_corr
    dview=None, **options['spatial_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 220, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 391, in regression_ipyparallel
    a_lrs = clf.fit(np.array(c.T), np.ravel(y))

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 699, in fit
    X, y = check_X_y(X, y, y_numeric=True, multi_output=True)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 576, in check_X_y
    dtype=None)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

- **If you're not reporting an error, type your message below**

**Comment by sebastiantiesmeyer** [comment]
update: one source of nan values is the dot product in intialization.py, ln 1055

**Comment by j-friedrich** [comment]
The errors in the stack trace you posted starts with a divide by zero RuntimeWarning. The noise value of (at least) one pixel is zero. Do you have one pixel that is just a constant value for all frames? 
Try adding a small value to `noise_pixel` when calculating `pnr` in line 1305:
`pnr = np.divide(data_max, noise_pixel+np.finfo(float).eps)`
This might however only get rid of the RuntimeWarnings, seems the code deals gracefully with nans in `pnr`.

Re: update
Does the `scipy.linalg.lstsq` in 1733 return nans in spite of the input matrices containing only finite numbers? Or do the input matrices already have nans?

**Comment by sebastiantiesmeyer** [comment]
These runtime warnings pop up all over the place (also for the runs that work out just fine) ; I'll ignore them for now. 

The initialization.py appears to pad edges; these padding regions have a constant value for what I understand.

For what I've checked, the input did not contain nans (these sparse matrices are not very transparent, though). Applying np.nan_to_num() on the output of compute_W(...) renders a new error: 

 ```
 File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 97, in extract_spikes
    cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 457, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1074, in greedyROI_corr
    dview=None, **options['spatial_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 220, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 391, in regression_ipyparallel
    a_lrs = clf.fit(np.array(c.T), np.ravel(y))

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 709, in fit
    Xy=Xy)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 648, in _fit
    return_n_iter=True, positive=self.positive)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 345, in lars_path
    lower=True)

error: (shape(c,0)==shape(b,0)) failed for 2nd argument b

```

**Comment by j-friedrich** [comment]
Puzzling. Tried hard, but the only way I got `scipy.linalg.lstsq` to return nans was to provide np.inf as second argument. To be sure that's not what's happening, can you set `check_finite=True` in line 1733 to see whether it triggers `ValueError: array must not contain infs or NaNs`

`np.nan_to_num` doesn't work directly with sparse matrices. You would need to access the internals of the sparse representation and do `W.data = np.nan_to_num(W.data)`

**Comment by sebastiantiesmeyer** [comment]
check_finite does not lead to any different outcome. lstsq should in any way complain if there's nan or inf input. For debugging, I added the line 
```
print('B :',B.sum(),' Y: ',Y.sum(),' data: ',np.sum(data),' X: ',X.sum(),' X[p]: ',X[p])
```
at line 1735, after the data += gets pushed.

Output:
```
Compute Background
B : 9.420959  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 48.019897  46.861603  45.609497 ... -17.113724 -14.440079 -11.876175]
B : 6.805786  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 8.100891  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 9.168488  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 7.328705  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 11.287506  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 12.599609  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 7.7345276  7.525055   7.2986145 ... -2.3356934 -1.9223022 -1.5259094]
B : 5.555664  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [17.116058  17.116058  17.116058  ... -7.3797913 -5.7306213 -4.1948853]
B : 6.40625  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [13.413849  13.413849  13.413849  ... -5.5471497 -4.2516174 -3.0475464]
B : 7.687744  Y:  40996680000.0  data:  -4.7146894e+17  X:  303.35938  X[p]:  [ 9.491241   9.491241   9.491241  ... -3.604065  -2.6859741 -1.8356323]
B : 6.373047  Y:  40996680000.0  data:  -4.997494e+17  X:  303.35938  X[p]:  [ 9.491241   9.491241   9.491241  ... -3.604065  -2.6859741 -1.8356323]
B : 7.0722656  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [ 9.491241   9.491241   9.491241  ... -3.604065  -2.6859741 -1.8356323]
B : 4.5429688  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [ 1.6669006  1.6669006  1.6669006 ... -1.4145813 -1.2875671 -1.165802 ]
B : 5.4697266  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [3.0517578e-05 3.0517578e-05 3.0517578e-05 ... 3.0517578e-05 3.0517578e-05
 3.0517578e-05]
B : 7.269043  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [ 6.4496155  6.4496155  6.4496155 ... -5.485199  -4.994293  -4.5235596]
B : 9.897583  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [11.548981   10.993408   10.767883   ... -0.38583374  0.10507202
  0.57580566]
B : 6.726898  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [11.548981   10.993408   10.767883   ... -0.38583374  0.10507202
  0.57580566]
B : 9.633972  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [11.548981   10.993408   10.767883   ... -0.38583374  0.10507202
  0.57580566]
B : 11.491333  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [12.296204   11.740631   11.515106   ... -0.9476929  -0.35610962
  0.20727539]
B : 10.643066  Y:  40996680000.0  data:  nan  X:  303.35938  X[p]:  [13.253387   12.697815   12.47229    ... -1.6868896  -0.97872925
 -0.30749512]

...
...

```

So nans are introduced at this point apparrently...

**Comment by sebastiantiesmeyer** [comment]
The problem was casting the numpy array to a python list and back, replacing the line with 

data = np.concatenate([data,(scipy.linalg.lstsq(B.T, Y[p] - A[p].dot(C) - b0[p] if X is None else X[p], check_finite=False)[0])])

works just fine : )

**Comment by j-friedrich** [comment]
Thanks for figuring out a solution. Not sure why the faster implementation using lists yields errors, but will change it to your suggested concatenation of arrays.

**Comment by j-friedrich** [comment]
Incorporated your solution @sebastiantiesmeyer, thus closing.

**Comment by sebastiantiesmeyer** [comment]
Sorry, I actually deleted this comment over a week ago, since it turned out
to be wrong. I am still in the process of making our one-photon footage
 run on caiman. At this point, I have made the following changes:

Eventually, I just commented out the entire 'try' block in
initialization.py, [1727] and let the catch run as default. The running
time did not increase dramatically, but the invalid results (caused by
np.inv()) went away; I would advice either discarding the try or replacing
the try/catch with a written-out, informed case distinction.

This leads to another source of NaNs in merging.py, [265], where
apparrently (computedC x computedC)  produces a zero divisor. For now, I
added a line
```if (computedC * computedC.T) == 0: break```
to merging.py, [265]

I could not find the last source of NaNs, but changed spatial.py [379] to
```if np.size(c) > 0 and not any(np.isnan(c)):```
, which at least prevents NaNs from entering ```clf.fit(np.array(c.T),
np.ravel(y))```.

For now, the pipeline seems to work for my test dataset. I will write you
another mail once I have confirmed more pipeline runs on other data of
ours. You can however revert the changes I suggested in my deleted comment
and use the faster native python implementation; my apologies again, but
these try/catch blocks are a nightmare to debug : / .

**Comment by j-friedrich** [comment]
Hi @sebastiantiesmeyer,
I managed to come up with parameter settings where line 391, `clf.fit(np.array(c.T), np.ravel(y))` fails, as it does for you. I made some changes to the code that fixed the error I got and am hopeful it fixes your issues too. To avoid the singular matrix I now just add a small diagonal matrix. I also added the removal of empty components to merging.
I pushed to branch issue323. Can you please do a checkout and see whether it runs through on your data. If it does I'll proceed with merging into master.

**Comment by sebastiantiesmeyer** [comment]
Great job! Works like a charm until (nearly) the very end, but that's a different issue: 
https://github.com/flatironinstitute/CaImAn/issues/335

**Comment by sebastiantiesmeyer** [comment]
Taking that back. For some input, initialization.py still fails on singular matrices at the same point:


  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 167, in <module>
    Ain = extract_spikes(jobs[0],output_loc,bord_px = 0, multiprocessing = parser.parse_args().M)

  File "/scratch/stiesmeyer/code/CaImAn/RadboudMemDyn/CaliPipeline/CaliExtract_orig.py", line 99, in extract_spikes
    cnm.fit(Y)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 577, in fit
    del_duplicates=self.del_duplicates)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 278, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 463, in fit
    Y, sn=sn, options_total=options, **options['init_params'])

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1053, in greedyROI_corr
    A, C, (d1, d2), ring_size_factor * gSiz, ssub=ssub_B)

  File "/scratch/stiesmeyer/code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1732, in compute_W
    data += list(np.linalg.inv(tmp).

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 528, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "/scratch/stiesmeyer/code/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix

**Comment by sebastiantiesmeyer** [comment]
btw, I think you might need to rewrite the ' if X is None' checks in the calculation of B and tmp since the execution will never arrive there but rather throw an error at xrange(len(X))

**Comment by j-friedrich** [comment]
You're right about the `None`. The (currently actually uncalled) serial code also hasn't been updated to include downsampling. 
Seems like the added diagonal was too small. Let's try a value that matches the scale of the data instead of being fixed. Can you please try whether it runs through if you change line 1730 from `tmp = np.array(B.dot(B.T)) + np.finfo(np.float32).eps * np.eye(len(B), dtype='float32')` to `tmp = np.array(B.dot(B.T))` `tmp += np.finfo(np.float32).eps * np.eye(len(B), dtype='float32') * tmp.min()`
Does `tmp` by any chance contain `inf`? If that's the case we would have to scale by the number of frames. I still don't get why my original version to just try to invert and if that fails use lstsq instead didn't do the job.

**Comment by sebastiantiesmeyer** [comment]
This is not sufficient either. There are no nan/inf in tmp. Maybe take the pseudo-inverse instead?

**Comment by sebastiantiesmeyer** [comment]
Furthermore, the dimensions of your multiplication do not end up. B^-1 turns out to be [n_px_ring,n_px_ring], whereas X[p] is [n_frames / factor_downsampling]

**Comment by j-friedrich** [comment]
Using the pseudinverse is even slower than lstsq, and solving the least squares problem for each pixel is the computational bottleneck.
Nevertheless, does always using the slower fallback 
`data += list(scipy.linalg.lstsq(B.T, Y[p] - A[p].dot(C) - b0[p]
if X is None else X[p], check_finite=False)[0])` in line 1731 as default actually resolve all issues?

**Comment by sebastiantiesmeyer** [comment]
That was my original proposition, actually. 
I tried it for now, one time the run failed there with:
``` LinAlgError: SVD did not converge ```

When I tried a second run with exactly the same settings afterwards, the run failed at good old spatial.py, [391]:
``` ValueError: Input contains NaN, infinity or a value too large for dtype('float32'). ```

Very puzzling indeed...

**Comment by j-friedrich** [comment]
Can you wrap the `scipy.linalg.lstsq` line in a try except clause, save the matrix B and vector X[p] when the exception occurs and share them with me, so that I can look at the concrete example?

**Comment by sebastiantiesmeyer** [comment]
I will try to do that tomorrow. One question: How deterministic is the actual algorithm? Does it include name-worthy randomization (there's one in e.g. estimate_time_constant())? Are the patches evaluated in a random sequence for dview = None? And are the .mmap files altered/corrupted during the process?

**Comment by sebastiantiesmeyer** [comment]
Can you give me a working e-mail address so I can contact you?

**Comment by j-friedrich** [comment]
The one in git log is fine:
jfriedrich at flatironinstitute.org

**Comment by j-friedrich** [comment]
Thanks. The values obtained with numpy differ quite a bit from scipy and are too extreme. We need to add a diagonal to the potentially singular matrix that doesn't just try to avoid the numerical issue but regularizes the values of W. I checked PC's matlab code and he is much more aggressive with the Tikhonov regularization. I updated the issue323 branch to use his values. Please check whether the errors are now gone.

**Comment by sebastiantiesmeyer** [comment]
I think we're save to merge it into master.

**Comment by j-friedrich** [comment]
Thanks for keeping me posted. Merged into master.
