### ISSUE TITLE
Issues installing caimanmanager.py

### ISSUE THREAD

**Issue by kareemcheese96** [flatironinstitute/CaImAn#410]
@pgunn continuing off of the issue on gitter, I performed the conda update opencv numpy within the environment. After doing so and attempting the python caimanmanager.py install, I received a different issue. The following error message came up: 
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out[slc] = structure != 0
Traceback (most recent call last):
  File "caimanmanager.py", line 12, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\SvendsenLab\CaImAn\caiman\__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\SvendsenLab\CaImAn\caiman\base\movies.py", line 67, in <module>
    from ..utils import visualization
  File "C:\Users\SvendsenLab\CaImAn\caiman\utils\visualization.py", line 34, in <module>
    from ..summary_images import local_correlations
  File "C:\Users\SvendsenLab\CaImAn\caiman\summary_images.py", line 31, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "C:\Users\SvendsenLab\CaImAn\caiman\source_extraction\cnmf\__init__.py", line 12, in <module>
    from . import oasis
ImportError: cannot import name 'oasis'

**Comment by pgunn** [comment]
If you reinstall caiman with pip it should fix the issue.

**Comment by kareemcheese96** [comment]
I reinstalled caiman with pip, but I then got the same error as above when I wrote in "python caimanmanager.py install"

**Comment by pgunn** [comment]
What you'll want to do is copy caimanmanager.py outside the caiman folder, and run it there.

**Comment by kareemcheese96** [comment]
@pgunn Great, thank you for all of your help! It worked now.

**Comment by omidm7** [comment]
Hi, I'm having the same issue as @kareemcheese96 . Can you explain what you mean by "copy caimanmanager.py outside the caiman folder, and run it there." I tried moving the .py file and running caimanmanager.py install from the terminal and I still get the oasis error. Sorry, I am very new at this.

**Comment by pgunn** [comment]
@omidm7 Do you mind making a new issue for this? I don't want to bother kareemcheese96 with the conversation. Happy to help you though!
